### ISSUE TITLE
onConnect AssertionError

### ISSUE THREAD

**Issue by Deadly0** [request/tunnel-agent#20]
Is someone can help me understand with this error happens when i make request using nodejs package `request`? What this error means.

```
AssertionError: 20 == 0
  at ClientRequest.onConnect (/home/carmod/www/avitoparser/bundle/programs/server/npm/node_modules/tunnel-agent/index.js:159:14)
  at ClientRequest.g (events.js:260:16)
  at emitThree (events.js:97:13)
  at ClientRequest.emit (events.js:175:7)
  at Socket.socketOnData (_http_client.js:354:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:536:20)
```

**Comment by seanc** [comment]
having the same issue

**Comment by imajus** [comment]
Same problem here.

**Comment by gvuyk** [comment]
In my case it seems to happen when an http proxy is used to connect to some site with https

**Comment by kevinstubbs** [comment]
@gvuyk thank you so much! I was able to work around the issue with that. This exception was going uncaught from the main request module and randomly crashing my entire application @.@

**Comment by timbowhite** [comment]
The [```assert``` on the head variable](https://github.com/request/tunnel-agent/blob/master/index.js#L160) makes this an uncatchable error.  Why is it necessary?

**Comment by phibya** [comment]
Same issue here

```
AssertionError: 120 == 0
    at ClientRequest.onConnect (/home/meteor/ACWebService/bundle/programs/server/npm/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

**Comment by jancurn** [comment]
+1

**Comment by Woor** [comment]
This package seems to be unmaintained/dead...

**Comment by mike442144** [comment]
It is another bug actually, you guys could use my [repo](https://github.com/bda-research/tunnel-agent) instead, it is forked from this repo, and fixed two critical bugs. if you don't know how to use it, refer to npm-shrinkwrap.json

This repo seems dead and I'm considering how to solve it. Maybe @mikeal should transfer this repo.

**Comment by dryhumor** [comment]
In my case Avast (security software running on my development computer) was causing the error, specifically the Web Shield feature. Adding our proxy server to the Web Shield "Excluded servers" list made the error go away.

**Comment by DanNi0130** [comment]
In case anyone finds this later, as @mike442144 said, you can fix this problem by using his module with this command:
npm install --save git+https://git@github.com/bda-research/tunnel-agent.git

**Comment by SacDin** [comment]
+1
same issue while using http proxy with https url
