### ISSUE TITLE
Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by Joel-Haeberli** [request/tunnel-agent#31]
Hey Guys 
I'm writing e2e-Tests (with Protractor) at the moment and now im stucked cause of following error:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: tunneling socket could not be established, cause=write EPROTO 140252687583040:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    at ClientRequest.onError (/home/dev/development/projects/ebd_webui/ebd-web-ui/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:481:13)
    at TLSSocket.Socket._destroy (net.js:522:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:10)
```

And I'm really at the end of my ideas and nerves. Can anyone help me out with this? Would really appreciate it!

**Comment by Joel-Haeberli** [comment]
Had the wrong versions installed. After updating nodejs and npm it worked.
